CREATE TABLE TARIFFS (
    TARIFF_ID      NUMBER PRIMARY KEY,
    NAME           VARCHAR2(100) NOT NULL,
    MONTHLY_FEE    NUMBER NOT NULL,
    DATA_LIMIT     NUMBER NOT NULL,
    MINUTE_LIMIT   NUMBER NOT NULL,
    SMS_LIMIT      NUMBER NOT NULL
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID    NUMBER PRIMARY KEY,
    NAME           VARCHAR2(100) NOT NULL,
    CITY           VARCHAR2(100) NOT NULL,
    SIGNUP_DATE    DATE NOT NULL,
    TARIFF_ID      NUMBER NOT NULL,
    CONSTRAINT FK_CUSTOMERS_TARIFF
        FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
    ID             NUMBER PRIMARY KEY,
    CUSTOMER_ID    NUMBER NOT NULL,
    DATA_USAGE     NUMBER(10,2) NOT NULL,
    MINUTE_USAGE   NUMBER NOT NULL,
    SMS_USAGE      NUMBER NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_MONTHLY_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT CHK_PAYMENT_STATUS
        CHECK (PAYMENT_STATUS IN ('PAID', 'UNPAID', 'LATE'))
);

CREATE INDEX IDX_CUSTOMERS_TARIFF_ID
    ON CUSTOMERS(TARIFF_ID);

CREATE INDEX IDX_MONTHLY_STATS_CUSTOMER_ID
    ON MONTHLY_STATS(CUSTOMER_ID);

CREATE INDEX IDX_CUSTOMERS_SIGNUP_DATE
    ON CUSTOMERS(SIGNUP_DATE);